# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.



# Site settings
title: Eren Ulaş
email: eren.ulas@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Eren Ulaş. A software developer and a computer engineering student at Marmara University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erenulas.github.io" # the base hostname & protocol for your site
author: Eren Ulaş
github_username: erenulas
linkedin_username: erenulas
repository: erenulas/erenulas.github.io
logo: favicon.ico
social:
  name: Eren Ulaş
  links:
    - https://www.linkedin.com/in/erenulas/
    - https://github.com/erenulas


plugins:
  - jekyll-seo-tag
  - "jekyll-github-metadata"
  - "jekyll-sitemap"

# Build settings
markdown: kramdown
